
// ============================================================
// LANGUAGES & UI TEXT
// ============================================================

const LANGUAGES = {
  de: { name: 'Deutsch',     flag: '🇩🇪' },
  vi: { name: 'Tiếng Việt',  flag: '🇻🇳' },
  en: { name: 'English',     flag: '🇬🇧' },
  tr: { name: 'Türkçe',      flag: '🇹🇷' },
  ar: { name: 'العربية',      flag: '🇸🇦' },
  es: { name: 'Español',     flag: '🇪🇸' },
  fr: { name: 'Français',    flag: '🇫🇷' },
  uk: { name: 'Українська',  flag: '🇺🇦' },
  pl: { name: 'Polski',      flag: '🇵🇱' }
};

const UI_TEXT = {
  de: {
    title: 'Gefühle-Memory',
    subtitle: 'Finde die Paare — und sprich über deine Gefühle',
    moves: 'Züge',
    pairs: 'Paare',
    time: 'Zeit',
    newGame: 'Neues Spiel',
    modeClassic: 'Klassisch',
    modeStory: 'Geschichten',
    modeTalk: 'Gesprächsrunde',
    modeCheckin: 'Check-in',
    langLabel: 'Sprachen',
    pairFound: 'Paar gefunden!',
    promptIntro: 'Gesprächsimpuls:',
    congratsTitle: '🎉 Geschafft!',
    congratsText: 'Du hast alle Paare gefunden!',
    congratsStats: '{moves} Züge in {time}',
    playAgain: 'Nochmal spielen',
    storyIntro: 'Erzähl eine kurze Geschichte, in der diese Gefühle vorkommen:',
    talkIntro: 'Zieh eine Karte und erzähl davon:',
    drawCard: 'Karte ziehen',
    newCards: 'Neue Karten',
    allCategories: 'Alle Kategorien',
    share: 'Teilen',
    shareText: 'Ich spiele Gefühle-Memory — ein Spiel über Emotionen in {lang1} und {lang2}! 💛',
    checkinTitle: 'Was brauchst du heute?',
    checkinSubtitle: 'Wähle in jeder Dimension, was sich gerade richtig anfühlt.',
    todayIChoose: 'Heute wähle ich:',
    checkinDone: '🌿 Gut gemacht. Hör auf dich.',
    checkinReset: 'Neu beginnen',
    tapToContinue: 'Tippe irgendwo um weiterzumachen',
    tapToClose: 'Tippe zum Schließen',
    speak: 'Aussprechen',
    darkMode: 'Dunkelmodus',
    stars: 'Sterne',
    bestScore: 'Bestleistung',
    newBest: 'Neuer Rekord!',
    modeWheel: 'Rad',
    wheelIntro: 'Erkunde alle 67 Gefühle im Rad',
    solo: 'Solo',
    multiPlayer: 'Mehrspieler',
    player: 'Spieler',
    playerTurn: '{name} ist dran',
    points: 'Punkte',
    winner: 'Gewinner!',
    tie: 'Unentschieden!',
    passDevice: 'Weiter an {name}',
    enterNames: 'Spielernamen eingeben',
    startGame: 'Spiel starten',
    scoreboard: 'Punktestand',
    modeJournal: 'Journal',
    journalTitle: 'Wie fühlst du dich heute?',
    journalNote: 'Möchtest du mehr erzählen?',
    journalSave: 'Speichern',
    journalHistory: 'Vergangene Einträge',
    journalPattern: '🤖 Muster erkennen',
    journalNoEntries: 'Noch keine Einträge.',
    journalSaved: '✓ Gespeichert!',
    journalWeek: 'Diese Woche',
    aiGenerate: '🤖 Kulturellen Einblick generieren',
    aiLoading: 'Wird generiert...',
    aiSetup: 'KI-Schlüssel in ⚙️ Einstellungen einrichten',
    settings: 'Einstellungen',
    modeLearn: 'Lernen',
    learnTitle: 'Vokabel-Trainer',
    learnSubtitle: 'Lerne Gefühle mit Karteikarten und Wiederholung',
    dueToday: 'Heute fällig',
    studyNow: 'Weiter lernen',
    lastStudied: 'Zuletzt gelernt',
    correct: 'Richtig',
    wrong: 'Falsch',
    sessionComplete: 'Runde abgeschlossen!',
    score: 'Ergebnis',
    newLearned: 'Neu gelernt',
    toReview: 'Zum Wiederholen',
    masteryNew: 'Neu',
    masteryLearning: 'Lernend',
    masteryKnown: 'Bekannt',
    masteryMastered: 'Gemeistert',
    exportProgress: 'Fortschritt exportieren',
    streak: 'Serie',
    streakDays: 'Tage',
    exercisePrompt: 'Übung',
    nextCard: 'Nächste Karte',
    backToDashboard: 'Zurück',
    nochmal: 'Nochmal',
    categoryBreakdown: 'Kategorien'
  },
  vi: {
    title: 'Trò Chơi Cảm Xúc',
    subtitle: 'Tìm các cặp — và nói về cảm xúc của bạn',
    moves: 'Lượt',
    pairs: 'Cặp',
    time: 'Thời gian',
    newGame: 'Ván mới',
    modeClassic: 'Cổ điển',
    modeStory: 'Kể chuyện',
    modeTalk: 'Trò chuyện',
    modeCheckin: 'Tự vấn',
    langLabel: 'Ngôn ngữ',
    pairFound: 'Tìm được cặp!',
    promptIntro: 'Câu hỏi gợi ý:',
    congratsTitle: '🎉 Tuyệt vời!',
    congratsText: 'Bạn đã tìm được tất cả các cặp!',
    congratsStats: '{moves} lượt trong {time}',
    playAgain: 'Chơi lại',
    storyIntro: 'Kể một câu chuyện ngắn có những cảm xúc này:',
    talkIntro: 'Rút một thẻ và chia sẻ:',
    drawCard: 'Rút thẻ',
    newCards: 'Thẻ mới',
    allCategories: 'Tất cả',
    share: 'Chia sẻ',
    shareText: 'Tôi đang chơi Trò Chơi Cảm Xúc — trò chơi về cảm xúc bằng {lang1} và {lang2}! 💛',
    checkinTitle: 'Hôm nay bạn cần gì?',
    checkinSubtitle: 'Chọn trong mỗi chiều những gì cảm thấy phù hợp.',
    todayIChoose: 'Hôm nay tôi chọn:',
    checkinDone: '🌿 Tốt lắm. Hãy lắng nghe bản thân.',
    checkinReset: 'Bắt đầu lại',
    tapToContinue: 'Chạm bất kỳ đâu để tiếp tục',
    tapToClose: 'Chạm để đóng',
    speak: 'Phát âm',
    darkMode: 'Chế độ tối',
    stars: 'Sao',
    bestScore: 'Kỷ lục',
    newBest: 'Kỷ lục mới!',
    modeWheel: 'Vòng',
    wheelIntro: 'Khám phá tất cả 67 cảm xúc',
    solo: 'Một mình',
    multiPlayer: 'Nhiều người',
    player: 'Người chơi',
    playerTurn: 'Đến lượt {name}',
    points: 'Điểm',
    winner: 'Người thắng!',
    tie: 'Hòa!',
    passDevice: 'Chuyển cho {name}',
    enterNames: 'Nhập tên người chơi',
    startGame: 'Bắt đầu',
    scoreboard: 'Bảng điểm',
    modeJournal: 'Nhật ký',
    journalTitle: 'Hôm nay bạn cảm thấy thế nào?',
    journalNote: 'Bạn muốn chia sẻ thêm không?',
    journalSave: 'Lưu',
    journalHistory: 'Nhật ký trước',
    journalPattern: '🤖 Khám phá xu hướng',
    journalNoEntries: 'Chưa có nhật ký nào.',
    journalSaved: '✓ Đã lưu!',
    journalWeek: 'Tuần này',
    aiGenerate: '🤖 Tạo góc nhìn văn hóa',
    aiLoading: 'Đang tạo...',
    aiSetup: 'Cài đặt khóa AI trong ⚙️ Cài đặt',
    settings: 'Cài đặt',
    modeLearn: 'Học',
    learnTitle: 'Luyện từ vựng',
    learnSubtitle: 'Học cảm xúc với thẻ ghi nhớ và lặp lại',
    dueToday: 'Hôm nay cần ôn',
    studyNow: 'Học tiếp',
    lastStudied: 'Lần học gần nhất',
    correct: 'Đúng',
    wrong: 'Sai',
    sessionComplete: 'Hoàn thành phiên học!',
    score: 'Kết quả',
    newLearned: 'Mới học',
    toReview: 'Cần ôn lại',
    masteryNew: 'Mới',
    masteryLearning: 'Đang học',
    masteryKnown: 'Đã biết',
    masteryMastered: 'Thành thạo',
    exportProgress: 'Xuất tiến độ',
    streak: 'Chuỗi',
    streakDays: 'ngày',
    exercisePrompt: 'Bài tập',
    nextCard: 'Thẻ tiếp',
    backToDashboard: 'Quay lại',
    nochmal: 'Học lại',
    categoryBreakdown: 'Phân loại'
  },
  en: {
    title: 'Feelings Memory',
    subtitle: 'Find the pairs — and talk about your feelings',
    moves: 'Moves',
    pairs: 'Pairs',
    time: 'Time',
    newGame: 'New Game',
    modeClassic: 'Classic',
    modeStory: 'Stories',
    modeTalk: 'Talk Round',
    modeCheckin: 'Check-in',
    langLabel: 'Languages',
    pairFound: 'Pair found!',
    promptIntro: 'Talk about it:',
    congratsTitle: '🎉 Well done!',
    congratsText: 'You found all the pairs!',
    congratsStats: '{moves} moves in {time}',
    playAgain: 'Play again',
    storyIntro: 'Tell a short story that includes these feelings:',
    talkIntro: 'Draw a card and share:',
    drawCard: 'Draw card',
    newCards: 'New cards',
    allCategories: 'All categories',
    share: 'Share',
    shareText: "I'm playing Feelings Memory — a game about emotions in {lang1} and {lang2}! 💛",
    checkinTitle: 'What do you need today?',
    checkinSubtitle: 'Choose what feels right in each dimension.',
    todayIChoose: 'Today I choose:',
    checkinDone: '🌿 Well done. Listen to yourself.',
    checkinReset: 'Start over',
    tapToContinue: 'Tap anywhere to continue',
    tapToClose: 'Tap to close',
    speak: 'Pronounce',
    darkMode: 'Dark mode',
    stars: 'Stars',
    bestScore: 'Best score',
    newBest: 'New record!',
    modeWheel: 'Wheel',
    wheelIntro: 'Explore all 67 emotions on the wheel',
    solo: 'Solo',
    multiPlayer: 'Multiplayer',
    player: 'Player',
    playerTurn: "{name}'s turn",
    points: 'Points',
    winner: 'Winner!',
    tie: 'Tie!',
    passDevice: 'Pass to {name}',
    enterNames: 'Enter player names',
    startGame: 'Start game',
    scoreboard: 'Scoreboard',
    modeJournal: 'Journal',
    journalTitle: 'How are you feeling today?',
    journalNote: 'Want to share more?',
    journalSave: 'Save',
    journalHistory: 'Past entries',
    journalPattern: '🤖 Discover patterns',
    journalNoEntries: 'No entries yet.',
    journalSaved: '✓ Saved!',
    journalWeek: 'This week',
    aiGenerate: '🤖 Generate cultural insight',
    aiLoading: 'Generating...',
    aiSetup: 'Set up AI key in ⚙️ Settings',
    settings: 'Settings',
    modeLearn: 'Learn',
    learnTitle: 'Vocabulary Trainer',
    learnSubtitle: 'Learn emotions with flashcards and spaced repetition',
    dueToday: 'Due today',
    studyNow: 'Study now',
    lastStudied: 'Last studied',
    correct: 'Correct',
    wrong: 'Wrong',
    sessionComplete: 'Session complete!',
    score: 'Score',
    newLearned: 'New learned',
    toReview: 'To review',
    masteryNew: 'New',
    masteryLearning: 'Learning',
    masteryKnown: 'Known',
    masteryMastered: 'Mastered',
    exportProgress: 'Export progress',
    streak: 'Streak',
    streakDays: 'days',
    exercisePrompt: 'Exercise',
    nextCard: 'Next card',
    backToDashboard: 'Back',
    nochmal: 'Again',
    categoryBreakdown: 'Categories'
  },
  tr: {
    title: 'Duygu Hafıza Oyunu',
    subtitle: 'Eşleri bul — ve duygularını konuş',
    moves: 'Hamle',
    pairs: 'Çift',
    time: 'Süre',
    newGame: 'Yeni Oyun',
    modeClassic: 'Klasik',
    modeStory: 'Hikâyeler',
    modeTalk: 'Sohbet Turu',
    modeCheckin: 'Kontrol',
    langLabel: 'Diller',
    pairFound: 'Eş bulundu!',
    promptIntro: 'Sohbet sorusu:',
    congratsTitle: '🎉 Tebrikler!',
    congratsText: 'Tüm eşleri buldun!',
    congratsStats: '{time} içinde {moves} hamle',
    playAgain: 'Tekrar oyna',
    storyIntro: 'Bu duyguları içeren kısa bir hikâye anlat:',
    talkIntro: 'Bir kart çek ve paylaş:',
    drawCard: 'Kart çek',
    newCards: 'Yeni kartlar',
    allCategories: 'Tüm kategoriler',
    share: 'Paylaş',
    shareText: 'Duygu Hafıza Oyunu oynuyorum — {lang1} ve {lang2} dillerinde duygular hakkında bir oyun! 💛',
    checkinTitle: 'Bugün neye ihtiyacın var?',
    checkinSubtitle: 'Her boyutta sana uygun olanı seç.',
    todayIChoose: 'Bugün seçiyorum:',
    checkinDone: '🌿 Aferin. Kendini dinle.',
    checkinReset: 'Yeniden başla',
    tapToContinue: 'Devam etmek için dokun',
    tapToClose: 'Kapatmak için dokun',
    speak: 'Seslendir',
    darkMode: 'Karanlık mod',
    stars: 'Yıldızlar',
    bestScore: 'En iyi skor',
    newBest: 'Yeni rekor!',
    modeWheel: 'Çark',
    wheelIntro: 'Tüm 67 duyguyu çarkta keşfet',
    solo: 'Tek',
    multiPlayer: 'Çok oyunculu',
    player: 'Oyuncu',
    playerTurn: '{name} sırası',
    points: 'Puan',
    winner: 'Kazanan!',
    tie: 'Berabere!',
    passDevice: "{name}'a ver",
    enterNames: 'Oyuncu isimlerini gir',
    startGame: 'Oyunu başlat',
    scoreboard: 'Skor tablosu',
    modeJournal: 'Günlük',
    journalTitle: 'Bugün nasıl hissediyorsun?',
    journalNote: 'Daha fazla paylaşmak ister misin?',
    journalSave: 'Kaydet',
    journalHistory: 'Geçmiş kayıtlar',
    journalPattern: '🤖 Örüntüleri keşfet',
    journalNoEntries: 'Henüz kayıt yok.',
    journalSaved: '✓ Kaydedildi!',
    journalWeek: 'Bu hafta',
    aiGenerate: '🤖 Kültürel bakış oluştur',
    aiLoading: 'Oluşturuluyor...',
    aiSetup: '⚙️ Ayarlar\'dan AI anahtarını ayarla',
    settings: 'Ayarlar',
    modeLearn: 'Öğren',
    learnTitle: 'Kelime Antrenörü',
    learnSubtitle: 'Kartlarla ve aralıklı tekrarla duyguları öğren',
    dueToday: 'Bugün sırası',
    studyNow: 'Şimdi çalış',
    newCards: 'Yeni kartlar',
    lastStudied: 'Son çalışma',
    correct: 'Doğru',
    wrong: 'Yanlış',
    sessionComplete: 'Oturum tamamlandı!',
    score: 'Skor',
    newLearned: 'Yeni öğrenilen',
    toReview: 'Tekrar edilecek',
    masteryNew: 'Yeni',
    masteryLearning: 'Öğreniyor',
    masteryKnown: 'Bilinen',
    masteryMastered: 'Ustalaşmış',
    exportProgress: 'İlerlemeyi dışa aktar',
    streak: 'Seri',
    streakDays: 'gün',
    exercisePrompt: 'Alıştırma',
    nextCard: 'Sonraki kart',
    backToDashboard: 'Geri',
    nochmal: 'Tekrar',
    categoryBreakdown: 'Kategoriler'
  },
  ar: {
    title: 'لعبة ذاكرة المشاعر',
    subtitle: 'ابحث عن الأزواج — وتحدث عن مشاعرك',
    moves: 'حركات',
    pairs: 'أزواج',
    time: 'الوقت',
    newGame: 'لعبة جديدة',
    modeClassic: 'كلاسيكي',
    modeStory: 'قصص',
    modeTalk: 'جولة حوار',
    modeCheckin: 'تفقد',
    langLabel: 'اللغات',
    pairFound: 'تم إيجاد زوج!',
    promptIntro: 'سؤال للحوار:',
    congratsTitle: '🎉 أحسنت!',
    congratsText: 'لقد وجدت كل الأزواج!',
    congratsStats: '{moves} حركة في {time}',
    playAgain: 'العب مجدداً',
    storyIntro: 'اروِ قصة قصيرة تتضمن هذه المشاعر:',
    talkIntro: 'اسحب بطاقة وشارك:',
    drawCard: 'اسحب بطاقة',
    newCards: 'بطاقات جديدة',
    allCategories: 'جميع الفئات',
    share: 'مشاركة',
    shareText: 'أنا ألعب لعبة ذاكرة المشاعر — لعبة عن العواطف بـ{lang1} و{lang2}! 💛',
    checkinTitle: 'ماذا تحتاج اليوم؟',
    checkinSubtitle: 'اختر ما يناسبك في كل بُعد.',
    todayIChoose: 'اليوم أختار:',
    checkinDone: '🌿 أحسنت. استمع لنفسك.',
    checkinReset: 'ابدأ من جديد',
    tapToContinue: 'انقر في أي مكان للمتابعة',
    tapToClose: 'انقر للإغلاق',
    speak: 'انطق',
    darkMode: 'الوضع الداكن',
    stars: 'نجوم',
    bestScore: 'أفضل نتيجة',
    newBest: 'رقم قياسي جديد!',
    modeWheel: 'عجلة',
    wheelIntro: 'استكشف جميع المشاعر الـ67 على العجلة',
    solo: 'فردي',
    multiPlayer: 'متعدد اللاعبين',
    player: 'لاعب',
    playerTurn: 'دور {name}',
    points: 'نقاط',
    winner: 'الفائز!',
    tie: 'تعادل!',
    passDevice: 'مرر إلى {name}',
    enterNames: 'أدخل أسماء اللاعبين',
    startGame: 'ابدأ اللعبة',
    scoreboard: 'لوحة النتائج',
    modeJournal: 'يوميات',
    journalTitle: 'كيف تشعر اليوم؟',
    journalNote: 'هل تريد مشاركة المزيد؟',
    journalSave: 'حفظ',
    journalHistory: 'إدخالات سابقة',
    journalPattern: '🤖 اكتشف الأنماط',
    journalNoEntries: 'لا توجد إدخالات بعد.',
    journalSaved: '✓ تم الحفظ!',
    journalWeek: 'هذا الأسبوع',
    aiGenerate: '🤖 توليد رؤية ثقافية',
    aiLoading: 'جارٍ التوليد...',
    aiSetup: 'إعداد مفتاح AI في ⚙️ الإعدادات',
    settings: 'الإعدادات',
    modeLearn: 'تعلم',
    learnTitle: 'مدرب المفردات',
    learnSubtitle: 'تعلم المشاعر بالبطاقات والتكرار المتباعد',
    dueToday: 'مستحق اليوم',
    studyNow: 'ادرس الآن',
    newCards: 'بطاقات جديدة',
    lastStudied: 'آخر دراسة',
    correct: 'صحيح',
    wrong: 'خطأ',
    sessionComplete: 'اكتملت الجلسة!',
    score: 'النتيجة',
    newLearned: 'تعلم جديد',
    toReview: 'للمراجعة',
    masteryNew: 'جديد',
    masteryLearning: 'يتعلم',
    masteryKnown: 'معروف',
    masteryMastered: 'متقن',
    exportProgress: 'تصدير التقدم',
    streak: 'سلسلة',
    streakDays: 'أيام',
    exercisePrompt: 'تمرين',
    nextCard: 'البطاقة التالية',
    backToDashboard: 'رجوع',
    nochmal: 'مرة أخرى',
    categoryBreakdown: 'الفئات'
  },
  es: {
    title: 'Memoria de Sentimientos',
    subtitle: 'Encuentra las parejas — y habla sobre tus sentimientos',
    moves: 'Movimientos',
    pairs: 'Parejas',
    time: 'Tiempo',
    newGame: 'Nuevo Juego',
    modeClassic: 'Clásico',
    modeStory: 'Historias',
    modeTalk: 'Ronda de Charla',
    modeCheckin: 'Auto-revisión',
    langLabel: 'Idiomas',
    pairFound: '¡Pareja encontrada!',
    promptIntro: 'Pregunta para conversar:',
    congratsTitle: '🎉 ¡Muy bien!',
    congratsText: '¡Encontraste todas las parejas!',
    congratsStats: '{moves} movimientos en {time}',
    playAgain: 'Jugar de nuevo',
    storyIntro: 'Cuenta una historia corta que incluya estos sentimientos:',
    talkIntro: 'Saca una carta y comparte:',
    drawCard: 'Sacar carta',
    newCards: 'Nuevas cartas',
    allCategories: 'Todas las categorías',
    share: 'Compartir',
    shareText: 'Estoy jugando Memoria de Sentimientos — un juego sobre emociones en {lang1} y {lang2}! 💛',
    checkinTitle: '¿Qué necesitas hoy?',
    checkinSubtitle: 'Elige lo que se sienta bien en cada dimensión.',
    todayIChoose: 'Hoy elijo:',
    checkinDone: '🌿 Bien hecho. Escúchate.',
    checkinReset: 'Empezar de nuevo',
    tapToContinue: 'Toca en cualquier lugar para continuar',
    tapToClose: 'Toca para cerrar',
    speak: 'Pronunciar',
    darkMode: 'Modo oscuro',
    stars: 'Estrellas',
    bestScore: 'Mejor puntuación',
    newBest: '¡Nuevo récord!',
    modeWheel: 'Rueda',
    wheelIntro: 'Explora las 67 emociones en la rueda',
    solo: 'Solo',
    multiPlayer: 'Multijugador',
    player: 'Jugador',
    playerTurn: 'Turno de {name}',
    points: 'Puntos',
    winner: '¡Ganador!',
    tie: '¡Empate!',
    passDevice: 'Pasa a {name}',
    enterNames: 'Introduce nombres de jugadores',
    startGame: 'Empezar juego',
    scoreboard: 'Marcador',
    modeJournal: 'Diario',
    journalTitle: '¿Cómo te sientes hoy?',
    journalNote: '¿Quieres compartir más?',
    journalSave: 'Guardar',
    journalHistory: 'Entradas anteriores',
    journalPattern: '🤖 Descubrir patrones',
    journalNoEntries: 'Aún no hay entradas.',
    journalSaved: '✓ ¡Guardado!',
    journalWeek: 'Esta semana',
    aiGenerate: '🤖 Generar perspectiva cultural',
    aiLoading: 'Generando...',
    aiSetup: 'Configura la clave AI en ⚙️ Ajustes',
    settings: 'Ajustes',
    modeLearn: 'Aprender',
    learnTitle: 'Entrenador de Vocabulario',
    learnSubtitle: 'Aprende emociones con tarjetas y repetición espaciada',
    dueToday: 'Para hoy',
    studyNow: 'Estudiar ahora',
    newCards: 'Nuevas tarjetas',
    lastStudied: 'Último estudio',
    correct: 'Correcto',
    wrong: 'Incorrecto',
    sessionComplete: '¡Sesión completa!',
    score: 'Puntuación',
    newLearned: 'Recién aprendido',
    toReview: 'Para repasar',
    masteryNew: 'Nuevo',
    masteryLearning: 'Aprendiendo',
    masteryKnown: 'Conocido',
    masteryMastered: 'Dominado',
    exportProgress: 'Exportar progreso',
    streak: 'Racha',
    streakDays: 'días',
    exercisePrompt: 'Ejercicio',
    nextCard: 'Siguiente tarjeta',
    backToDashboard: 'Volver',
    nochmal: 'De nuevo',
    categoryBreakdown: 'Categorías'
  },
  fr: {
    title: 'Mémoire des Sentiments',
    subtitle: 'Trouve les paires — et parle de tes sentiments',
    moves: 'Coups',
    pairs: 'Paires',
    time: 'Temps',
    newGame: 'Nouvelle Partie',
    modeClassic: 'Classique',
    modeStory: 'Histoires',
    modeTalk: 'Tour de Parole',
    modeCheckin: 'Bilan',
    langLabel: 'Langues',
    pairFound: 'Paire trouvée!',
    promptIntro: 'Question de discussion:',
    congratsTitle: '🎉 Bravo!',
    congratsText: 'Tu as trouvé toutes les paires!',
    congratsStats: '{moves} coups en {time}',
    playAgain: 'Rejouer',
    storyIntro: 'Raconte une courte histoire avec ces sentiments:',
    talkIntro: 'Tire une carte et partage:',
    drawCard: 'Tirer une carte',
    newCards: 'Nouvelles cartes',
    allCategories: 'Toutes les catégories',
    share: 'Partager',
    shareText: 'Je joue à Mémoire des Sentiments — un jeu sur les émotions en {lang1} et {lang2}! 💛',
    checkinTitle: 'De quoi as-tu besoin aujourd\'hui?',
    checkinSubtitle: 'Choisis ce qui te convient dans chaque dimension.',
    todayIChoose: 'Aujourd\'hui je choisis:',
    checkinDone: '🌿 Bien joué. Écoute-toi.',
    checkinReset: 'Recommencer',
    tapToContinue: 'Touche n\'importe où pour continuer',
    tapToClose: 'Touche pour fermer',
    speak: 'Prononcer',
    darkMode: 'Mode sombre',
    stars: 'Étoiles',
    bestScore: 'Meilleur score',
    newBest: 'Nouveau record!',
    modeWheel: 'Roue',
    wheelIntro: 'Explore les 67 émotions sur la roue',
    solo: 'Solo',
    multiPlayer: 'Multijoueur',
    player: 'Joueur',
    playerTurn: 'Tour de {name}',
    points: 'Points',
    winner: 'Gagnant!',
    tie: 'Égalité!',
    passDevice: 'Passe à {name}',
    enterNames: 'Entrez les noms des joueurs',
    startGame: 'Commencer',
    scoreboard: 'Tableau des scores',
    modeJournal: 'Journal',
    journalTitle: 'Comment te sens-tu aujourd\'hui?',
    journalNote: 'Tu veux en dire plus?',
    journalSave: 'Sauvegarder',
    journalHistory: 'Entrées précédentes',
    journalPattern: '🤖 Découvrir des tendances',
    journalNoEntries: 'Pas encore d\'entrées.',
    journalSaved: '✓ Sauvegardé!',
    journalWeek: 'Cette semaine',
    aiGenerate: '🤖 Générer un aperçu culturel',
    aiLoading: 'Génération en cours...',
    aiSetup: 'Configure la clé AI dans ⚙️ Paramètres',
    settings: 'Paramètres',
    modeLearn: 'Apprendre',
    learnTitle: 'Entraîneur de Vocabulaire',
    learnSubtitle: 'Apprends les émotions avec des cartes et la répétition espacée',
    dueToday: 'À revoir aujourd\'hui',
    studyNow: 'Étudier maintenant',
    newCards: 'Nouvelles cartes',
    lastStudied: 'Dernière étude',
    correct: 'Correct',
    wrong: 'Faux',
    sessionComplete: 'Session terminée!',
    score: 'Score',
    newLearned: 'Nouvellement appris',
    toReview: 'À réviser',
    masteryNew: 'Nouveau',
    masteryLearning: 'En apprentissage',
    masteryKnown: 'Connu',
    masteryMastered: 'Maîtrisé',
    exportProgress: 'Exporter le progrès',
    streak: 'Série',
    streakDays: 'jours',
    exercisePrompt: 'Exercice',
    nextCard: 'Carte suivante',
    backToDashboard: 'Retour',
    nochmal: 'Encore',
    categoryBreakdown: 'Catégories'
  },
  uk: {
    title: 'Пам\'ять Почуттів',
    subtitle: 'Знайди пари — і поговори про свої почуття',
    moves: 'Ходи',
    pairs: 'Пари',
    time: 'Час',
    newGame: 'Нова Гра',
    modeClassic: 'Класична',
    modeStory: 'Історії',
    modeTalk: 'Коло Розмов',
    modeCheckin: 'Самоперевірка',
    langLabel: 'Мови',
    pairFound: 'Пару знайдено!',
    promptIntro: 'Питання для розмови:',
    congratsTitle: '🎉 Молодець!',
    congratsText: 'Ти знайшов/ла всі пари!',
    congratsStats: '{moves} ходів за {time}',
    playAgain: 'Грати знову',
    storyIntro: 'Розкажи коротку історію з цими почуттями:',
    talkIntro: 'Витягни картку і поділися:',
    drawCard: 'Витягнути картку',
    newCards: 'Нові картки',
    allCategories: 'Усі категорії',
    share: 'Поділитися',
    shareText: 'Я граю в Пам\'ять Почуттів — гру про емоції мовами {lang1} та {lang2}! 💛',
    checkinTitle: 'Що тобі потрібно сьогодні?',
    checkinSubtitle: 'Обери те, що відчувається правильним у кожному вимірі.',
    todayIChoose: 'Сьогодні я обираю:',
    checkinDone: '🌿 Молодець. Слухай себе.',
    checkinReset: 'Почати спочатку',
    tapToContinue: 'Торкнись будь-де, щоб продовжити',
    tapToClose: 'Торкнись, щоб закрити',
    speak: 'Вимовити',
    darkMode: 'Темний режим',
    stars: 'Зірки',
    bestScore: 'Найкращий результат',
    newBest: 'Новий рекорд!',
    modeWheel: 'Колесо',
    wheelIntro: 'Досліджуй усі 67 емоцій на колесі',
    solo: 'Соло',
    multiPlayer: 'Багатокористувацька',
    player: 'Гравець',
    playerTurn: 'Хід {name}',
    points: 'Очки',
    winner: 'Переможець!',
    tie: 'Нічия!',
    passDevice: 'Передай {name}',
    enterNames: 'Введіть імена гравців',
    startGame: 'Почати гру',
    scoreboard: 'Таблиця результатів',
    modeJournal: 'Щоденник',
    journalTitle: 'Як ти почуваєшся сьогодні?',
    journalNote: 'Хочеш розказати більше?',
    journalSave: 'Зберегти',
    journalHistory: 'Попередні записи',
    journalPattern: '🤖 Виявити закономірності',
    journalNoEntries: 'Ще немає записів.',
    journalSaved: '✓ Збережено!',
    journalWeek: 'Цей тиждень',
    aiGenerate: '🤖 Створити культурний огляд',
    aiLoading: 'Генерується...',
    aiSetup: 'Налаштуй ключ AI в ⚙️ Налаштування',
    settings: 'Налаштування',
    modeLearn: 'Вчити',
    learnTitle: 'Тренажер Словника',
    learnSubtitle: 'Вивчай емоції з картками та інтервальним повторенням',
    dueToday: 'На сьогодні',
    studyNow: 'Вчити зараз',
    newCards: 'Нові картки',
    lastStudied: 'Останнє вивчення',
    correct: 'Правильно',
    wrong: 'Неправильно',
    sessionComplete: 'Сесію завершено!',
    score: 'Результат',
    newLearned: 'Нове вивчене',
    toReview: 'На повторення',
    masteryNew: 'Нове',
    masteryLearning: 'Вивчається',
    masteryKnown: 'Відоме',
    masteryMastered: 'Опановане',
    exportProgress: 'Експортувати прогрес',
    streak: 'Серія',
    streakDays: 'днів',
    exercisePrompt: 'Вправа',
    nextCard: 'Наступна картка',
    backToDashboard: 'Назад',
    nochmal: 'Ще раз',
    categoryBreakdown: 'Категорії'
  },
  pl: {
    title: 'Pamięć Uczuć',
    subtitle: 'Znajdź pary — i porozmawiaj o swoich uczuciach',
    moves: 'Ruchy',
    pairs: 'Pary',
    time: 'Czas',
    newGame: 'Nowa Gra',
    modeClassic: 'Klasyczna',
    modeStory: 'Historie',
    modeTalk: 'Runda Rozmów',
    modeCheckin: 'Samoocena',
    langLabel: 'Języki',
    pairFound: 'Para znaleziona!',
    promptIntro: 'Pytanie do rozmowy:',
    congratsTitle: '🎉 Świetnie!',
    congratsText: 'Znalazłeś/aś wszystkie pary!',
    congratsStats: '{moves} ruchów w {time}',
    playAgain: 'Zagraj ponownie',
    storyIntro: 'Opowiedz krótką historię z tymi uczuciami:',
    talkIntro: 'Wylosuj kartę i podziel się:',
    drawCard: 'Wylosuj kartę',
    newCards: 'Nowe karty',
    allCategories: 'Wszystkie kategorie',
    share: 'Udostępnij',
    shareText: 'Gram w Pamięć Uczuć — grę o emocjach w językach {lang1} i {lang2}! 💛',
    checkinTitle: 'Czego dziś potrzebujesz?',
    checkinSubtitle: 'Wybierz to, co czujesz jako właściwe w każdym wymiarze.',
    todayIChoose: 'Dziś wybieram:',
    checkinDone: '🌿 Dobrze. Słuchaj siebie.',
    checkinReset: 'Zacznij od nowa',
    tapToContinue: 'Dotknij gdziekolwiek, aby kontynuować',
    tapToClose: 'Dotknij, aby zamknąć',
    speak: 'Wymów',
    darkMode: 'Tryb ciemny',
    stars: 'Gwiazdki',
    bestScore: 'Najlepszy wynik',
    newBest: 'Nowy rekord!',
    modeWheel: 'Koło',
    wheelIntro: 'Odkrywaj wszystkie 67 emocji na kole',
    solo: 'Solo',
    multiPlayer: 'Wieloosobowa',
    player: 'Gracz',
    playerTurn: 'Tura {name}',
    points: 'Punkty',
    winner: 'Zwycięzca!',
    tie: 'Remis!',
    passDevice: 'Podaj {name}',
    enterNames: 'Wpisz imiona graczy',
    startGame: 'Rozpocznij grę',
    scoreboard: 'Tablica wyników',
    modeJournal: 'Dziennik',
    journalTitle: 'Jak się dziś czujesz?',
    journalNote: 'Chcesz powiedzieć więcej?',
    journalSave: 'Zapisz',
    journalHistory: 'Poprzednie wpisy',
    journalPattern: '🤖 Odkryj wzorce',
    journalNoEntries: 'Brak wpisów.',
    journalSaved: '✓ Zapisano!',
    journalWeek: 'Ten tydzień',
    aiGenerate: '🤖 Wygeneruj wgląd kulturowy',
    aiLoading: 'Generowanie...',
    aiSetup: 'Ustaw klucz AI w ⚙️ Ustawienia',
    settings: 'Ustawienia',
    modeLearn: 'Ucz się',
    learnTitle: 'Trener Słownictwa',
    learnSubtitle: 'Ucz się emocji z fiszkami i powtórkami',
    dueToday: 'Na dziś',
    studyNow: 'Ucz się teraz',
    newCards: 'Nowe karty',
    lastStudied: 'Ostatnia nauka',
    correct: 'Dobrze',
    wrong: 'Źle',
    sessionComplete: 'Sesja zakończona!',
    score: 'Wynik',
    newLearned: 'Nowo nauczone',
    toReview: 'Do powtórki',
    masteryNew: 'Nowe',
    masteryLearning: 'W nauce',
    masteryKnown: 'Znane',
    masteryMastered: 'Opanowane',
    exportProgress: 'Eksportuj postęp',
    streak: 'Seria',
    streakDays: 'dni',
    exercisePrompt: 'Ćwiczenie',
    nextCard: 'Następna karta',
    backToDashboard: 'Wróć',
    nochmal: 'Jeszcze raz',
    categoryBreakdown: 'Kategorie'
  }
};
