"""
Seed data — all 67 emotions extracted from js/data.js.

This is the single source of truth for the emotions table.
Called once on app startup if the emotions table is empty.

LEARNING NOTE:
- Seed data populates the database with initial/reference data
- We check first (if emotions table is empty) so re-deploys don't duplicate rows
- The emotion IDs here must match the IDs used in js/data.js exactly
"""

EMOTIONS = [
    # ── Licht & Weite (light) ─────────────────────────────────────────────────
    {"id": "freude",        "emoji": "😊", "category": "licht",   "name_de": "Freude",          "name_vi": "Niềm vui",              "name_en": "Joy",            "name_tr": "Sevinç",         "name_ar": "فرح",              "name_es": "Alegría",        "name_fr": "Joie",            "name_uk": "Радість",         "name_pl": "Radość",          "name_el": "Χαρά",            "name_ta": "மகிழ்ச்சி"},
    {"id": "dankbarkeit",   "emoji": "🙏", "category": "licht",   "name_de": "Dankbarkeit",      "name_vi": "Lòng biết ơn",          "name_en": "Gratitude",      "name_tr": "Şükran",         "name_ar": "امتنان",           "name_es": "Gratitud",       "name_fr": "Gratitude",       "name_uk": "Вдячність",       "name_pl": "Wdzięczność",     "name_el": "Ευγνωμοσύνη",    "name_ta": "நன்றியுணர்வு"},
    {"id": "frieden",       "emoji": "🕊️", "category": "licht",   "name_de": "Frieden",          "name_vi": "Bình an",               "name_en": "Peace",          "name_tr": "Huzur",          "name_ar": "سلام",             "name_es": "Paz",            "name_fr": "Paix",            "name_uk": "Спокій",          "name_pl": "Spokój",          "name_el": "Ειρήνη",         "name_ta": "அமைதி"},
    {"id": "leichtigkeit",  "emoji": "🎈", "category": "licht",   "name_de": "Leichtigkeit",     "name_vi": "Nhẹ nhõm",              "name_en": "Lightness",      "name_tr": "Hafiflik",       "name_ar": "خفة",              "name_es": "Ligereza",       "name_fr": "Légèreté",        "name_uk": "Легкість",        "name_pl": "Lekkość",         "name_el": "Ελαφρότητα",     "name_ta": "இலகுவான உணர்வு"},
    {"id": "begeisterung",  "emoji": "✨", "category": "licht",   "name_de": "Begeisterung",     "name_vi": "Hứng khởi",             "name_en": "Enthusiasm",     "name_tr": "Coşku",          "name_ar": "حماس",             "name_es": "Entusiasmo",     "name_fr": "Enthousiasme",    "name_uk": "Захоплення",      "name_pl": "Entuzjazm",       "name_el": "Ενθουσιασμός",   "name_ta": "உற்சாகம்"},
    {"id": "zaertlichkeit", "emoji": "🤲", "category": "licht",   "name_de": "Zärtlichkeit",     "name_vi": "Dịu dàng",              "name_en": "Tenderness",     "name_tr": "Şefkat",         "name_ar": "حنان",             "name_es": "Ternura",        "name_fr": "Tendresse",       "name_uk": "Ніжність",        "name_pl": "Czułość",         "name_el": "Τρυφερότητα",    "name_ta": "மென்மை"},
    {"id": "verbundenheit", "emoji": "🔗", "category": "licht",   "name_de": "Verbundenheit",    "name_vi": "Gắn kết",               "name_en": "Connection",     "name_tr": "Bağlılık",       "name_ar": "ترابط",            "name_es": "Conexión",       "name_fr": "Connexion",       "name_uk": "Єднання",         "name_pl": "Więź",            "name_el": "Σύνδεση",        "name_ta": "இணைப்புணர்வு"},
    {"id": "liebe",         "emoji": "❤️", "category": "licht",   "name_de": "Liebe",            "name_vi": "Tình yêu",              "name_en": "Love",           "name_tr": "Aşk",            "name_ar": "حب",               "name_es": "Amor",           "name_fr": "Amour",           "name_uk": "Любов",           "name_pl": "Miłość",          "name_el": "Αγάπη",          "name_ta": "அன்பு"},
    {"id": "staunen",       "emoji": "🤩", "category": "licht",   "name_de": "Staunen",          "name_vi": "Ngạc nhiên thích thú",  "name_en": "Wonder",         "name_tr": "Hayret",         "name_ar": "دهشة",             "name_es": "Asombro",        "name_fr": "Émerveillement",  "name_uk": "Подив",           "name_pl": "Zdumienie",       "name_el": "Θαυμασμός",      "name_ta": "வியப்பு"},
    {"id": "vertrauen",     "emoji": "🤝", "category": "licht",   "name_de": "Vertrauen",        "name_vi": "Tin tưởng",             "name_en": "Trust",          "name_tr": "Güven",          "name_ar": "ثقة",              "name_es": "Confianza",      "name_fr": "Confiance",       "name_uk": "Довіра",          "name_pl": "Zaufanie",        "name_el": "Εμπιστοσύνη",    "name_ta": "நம்பிக்கை"},
    {"id": "hoffnung",      "emoji": "🌱", "category": "licht",   "name_de": "Hoffnung",         "name_vi": "Hy vọng",               "name_en": "Hope",           "name_tr": "Umut",           "name_ar": "أمل",              "name_es": "Esperanza",      "name_fr": "Espoir",          "name_uk": "Надія",           "name_pl": "Nadzieja",        "name_el": "Ελπίδα",         "name_ta": "நம்பம்"},
    {"id": "klarheit",      "emoji": "💎", "category": "licht",   "name_de": "Klarheit",         "name_vi": "Sự rõ ràng",            "name_en": "Clarity",        "name_tr": "Netlik",         "name_ar": "وضوح",             "name_es": "Claridad",       "name_fr": "Clarté",          "name_uk": "Ясність",         "name_pl": "Jasność",         "name_el": "Διαύγεια",       "name_ta": "தெளிவு"},
    {"id": "freiheit",      "emoji": "🦅", "category": "licht",   "name_de": "Freiheit",         "name_vi": "Tự do",                 "name_en": "Freedom",        "name_tr": "Özgürlük",       "name_ar": "حرية",             "name_es": "Libertad",       "name_fr": "Liberté",         "name_uk": "Свобода",         "name_pl": "Wolność",         "name_el": "Ελευθερία",      "name_ta": "சுதந்திரம்"},
    {"id": "ehrfurcht",     "emoji": "🌌", "category": "licht",   "name_de": "Ehrfurcht",        "name_vi": "Kính trọng sâu sắc",    "name_en": "Awe",            "name_tr": "Huşu",           "name_ar": "رهبة",             "name_es": "Reverencia",     "name_fr": "Révérence",       "name_uk": "Благоговіння",    "name_pl": "Trwoga",          "name_el": "Δέος",           "name_ta": "ஆச்சரியம்"},

    # ── Sanfte Mitte (middle) ─────────────────────────────────────────────────
    {"id": "zufriedenheit",   "emoji": "😌", "category": "mitte",   "name_de": "Zufriedenheit",    "name_vi": "Hài lòng",              "name_en": "Contentment",    "name_tr": "Memnuniyet",     "name_ar": "رضا",              "name_es": "Satisfacción",   "name_fr": "Contentement",    "name_uk": "Задоволення",     "name_pl": "Zadowolenie",     "name_el": "Ικανοποίηση",    "name_ta": "திருப்தி"},
    {"id": "melancholie",     "emoji": "🌧️", "category": "mitte",   "name_de": "Melancholie",      "name_vi": "Man mác buồn",          "name_en": "Melancholy",     "name_tr": "Melankoli",      "name_ar": "كآبة",             "name_es": "Melancolía",     "name_fr": "Mélancolie",      "name_uk": "Меланхолія",      "name_pl": "Melancholia",     "name_el": "Μελαγχολία",     "name_ta": "மனச்சோர்வு"},
    {"id": "nachdenklichkeit","emoji": "🤔", "category": "mitte",   "name_de": "Nachdenklichkeit", "name_vi": "Trầm tư",               "name_en": "Thoughtfulness", "name_tr": "Düşüncelilik",   "name_ar": "تأمل",             "name_es": "Reflexión",      "name_fr": "Réflexion",       "name_uk": "Задумливість",    "name_pl": "Zamyślenie",      "name_el": "Στοχαστικότητα", "name_ta": "சிந்தனை"},
    {"id": "sehnsucht",       "emoji": "🥺", "category": "mitte",   "name_de": "Sehnsucht",        "name_vi": "Nhớ nhung",             "name_en": "Longing",        "name_tr": "Özlem",          "name_ar": "شوق",              "name_es": "Anhelo",         "name_fr": "Nostalgie",       "name_uk": "Туга",            "name_pl": "Tęsknota",        "name_el": "Νοσταλγία",      "name_ta": "ஏக்கம்"},
    {"id": "sensibilitaet",   "emoji": "🦋", "category": "mitte",   "name_de": "Sensibilität",     "name_vi": "Nhạy cảm",              "name_en": "Sensitivity",    "name_tr": "Hassasiyet",     "name_ar": "حساسية",           "name_es": "Sensibilidad",   "name_fr": "Sensibilité",     "name_uk": "Чутливість",      "name_pl": "Wrażliwość",      "name_el": "Ευαισθησία",     "name_ta": "உணர்வுமிகுதி"},
    {"id": "nostalgie",       "emoji": "📷", "category": "mitte",   "name_de": "Nostalgie",        "name_vi": "Hoài niệm",             "name_en": "Nostalgia",      "name_tr": "Nostalji",       "name_ar": "حنين",             "name_es": "Nostalgia",      "name_fr": "Nostalgie",       "name_uk": "Ностальгія",      "name_pl": "Nostalgia",       "name_el": "Αναπόληση",      "name_ta": "கடந்தகால நினைவு"},
    {"id": "offenheit",       "emoji": "🚪", "category": "mitte",   "name_de": "Offenheit",        "name_vi": "Cởi mở",                "name_en": "Openness",       "name_tr": "Açıklık",        "name_ar": "انفتاح",           "name_es": "Apertura",       "name_fr": "Ouverture",       "name_uk": "Відкритість",     "name_pl": "Otwartość",       "name_el": "Ανοιχτότητα",    "name_ta": "திறந்த மனம்"},
    {"id": "verletzlichkeit", "emoji": "🫧", "category": "mitte",   "name_de": "Verletzlichkeit",  "name_vi": "Dễ tổn thương",         "name_en": "Vulnerability",  "name_tr": "Kırılganlık",    "name_ar": "هشاشة",            "name_es": "Vulnerabilidad", "name_fr": "Vulnérabilité",   "name_uk": "Вразливість",     "name_pl": "Wrażliwość",      "name_el": "Ευαλωτότητα",    "name_ta": "பாதிப்புணர்வு"},
    {"id": "muedigkeit",      "emoji": "😴", "category": "mitte",   "name_de": "Müdigkeit",        "name_vi": "Mệt mỏi",               "name_en": "Tiredness",      "name_tr": "Yorgunluk",      "name_ar": "تعب",              "name_es": "Cansancio",      "name_fr": "Fatigue",         "name_uk": "Втома",           "name_pl": "Zmęczenie",       "name_el": "Κούραση",        "name_ta": "சோர்வு"},
    {"id": "langeweile",      "emoji": "🥱", "category": "mitte",   "name_de": "Langeweile",       "name_vi": "Chán chường",           "name_en": "Boredom",        "name_tr": "Can sıkıntısı",  "name_ar": "ملل",              "name_es": "Aburrimiento",   "name_fr": "Ennui",           "name_uk": "Нудьга",          "name_pl": "Nuda",            "name_el": "Πλήξη",          "name_ta": "சலிப்பு"},
    {"id": "neutralitaet",    "emoji": "⚖️", "category": "mitte",   "name_de": "Neutralität",      "name_vi": "Trung tính",            "name_en": "Neutrality",     "name_tr": "Tarafsızlık",    "name_ar": "حياد",             "name_es": "Neutralidad",    "name_fr": "Neutralité",      "name_uk": "Нейтральність",   "name_pl": "Neutralność",     "name_el": "Ουδετερότητα",   "name_ta": "நடுநிலை"},
    {"id": "beduerfnis",      "emoji": "🫶", "category": "mitte",   "name_de": "Bedürftigkeit",    "name_vi": "Cần được quan tâm",     "name_en": "Neediness",      "name_tr": "Muhtaçlık",      "name_ar": "احتياج",           "name_es": "Necesidad",      "name_fr": "Besoin",          "name_uk": "Потреба",         "name_pl": "Potrzeba",        "name_el": "Ανάγκη",         "name_ta": "தேவையுணர்வு"},
    {"id": "weichheit",       "emoji": "☁️", "category": "mitte",   "name_de": "Weichheit",        "name_vi": "Mềm mỏng",              "name_en": "Softness",       "name_tr": "Yumuşaklık",     "name_ar": "لين",              "name_es": "Suavidad",       "name_fr": "Douceur",         "name_uk": "М'якість",        "name_pl": "Miękkość",        "name_el": "Απαλότητα",      "name_ta": "மென்மையான மனம்"},

    # ── Schwere & Tiefe (heavy) ───────────────────────────────────────────────
    {"id": "traurigkeit",      "emoji": "😢", "category": "schwere", "name_de": "Traurigkeit",      "name_vi": "Buồn bã",               "name_en": "Sadness",        "name_tr": "Üzüntü",         "name_ar": "حزن",              "name_es": "Tristeza",       "name_fr": "Tristesse",       "name_uk": "Сум",             "name_pl": "Smutek",          "name_el": "Θλίψη",          "name_ta": "துக்கம்"},
    {"id": "einsamkeit",       "emoji": "🌙", "category": "schwere", "name_de": "Einsamkeit",       "name_vi": "Cô đơn",                "name_en": "Loneliness",     "name_tr": "Yalnızlık",      "name_ar": "وحدة",             "name_es": "Soledad",        "name_fr": "Solitude",        "name_uk": "Самотність",      "name_pl": "Samotność",       "name_el": "Μοναξιά",        "name_ta": "தனிமை"},
    {"id": "enttaeuschung",    "emoji": "😞", "category": "schwere", "name_de": "Enttäuschung",     "name_vi": "Thất vọng",             "name_en": "Disappointment", "name_tr": "Hayal kırıklığı","name_ar": "خيبة أمل",         "name_es": "Decepción",      "name_fr": "Déception",       "name_uk": "Розчарування",    "name_pl": "Rozczarowanie",   "name_el": "Απογοήτευση",    "name_ta": "ஏமாற்றம்"},
    {"id": "hilflosigkeit",    "emoji": "😶", "category": "schwere", "name_de": "Hilflosigkeit",    "name_vi": "Bất lực",               "name_en": "Helplessness",   "name_tr": "Çaresizlik",     "name_ar": "عجز",              "name_es": "Impotencia",     "name_fr": "Impuissance",     "name_uk": "Безпорадність",   "name_pl": "Bezradność",      "name_el": "Αβοηθησία",      "name_ta": "இயலாமை"},
    {"id": "ueberforderung",   "emoji": "🤯", "category": "schwere", "name_de": "Überforderung",    "name_vi": "Quá tải",               "name_en": "Overwhelm",      "name_tr": "Bunalmışlık",    "name_ar": "إرهاق",            "name_es": "Agobio",         "name_fr": "Surcharge",       "name_uk": "Перевантаження",  "name_pl": "Przeciążenie",    "name_el": "Υπερφόρτωση",    "name_ta": "அதிக சுமை"},
    {"id": "ohnmacht",         "emoji": "🕳️", "category": "schwere", "name_de": "Ohnmacht",         "name_vi": "Bất lực hoàn toàn",     "name_en": "Powerlessness",  "name_tr": "Güçsüzlük",      "name_ar": "عجز تام",          "name_es": "Impotencia total","name_fr": "Impuissance totale","name_uk": "Безсилля",       "name_pl": "Bezsilność",      "name_el": "Αδυναμία",       "name_ta": "சக்தியின்மை"},
    {"id": "scham",            "emoji": "😳", "category": "schwere", "name_de": "Scham",            "name_vi": "Xấu hổ",                "name_en": "Shame",          "name_tr": "Utanç",          "name_ar": "خجل",              "name_es": "Vergüenza",      "name_fr": "Honte",           "name_uk": "Сором",           "name_pl": "Wstyd",           "name_el": "Ντροπή",         "name_ta": "வெட்கம்"},
    {"id": "schuld",           "emoji": "⚖️", "category": "schwere", "name_de": "Schuld",           "name_vi": "Tội lỗi",               "name_en": "Guilt",          "name_tr": "Suçluluk",       "name_ar": "ذنب",              "name_es": "Culpa",          "name_fr": "Culpabilité",     "name_uk": "Провина",         "name_pl": "Poczucie winy",   "name_el": "Ενοχή",          "name_ta": "குற்றவுணர்வு"},
    {"id": "leere",            "emoji": "🫥", "category": "schwere", "name_de": "Leere",            "name_vi": "Trống rỗng",            "name_en": "Emptiness",      "name_tr": "Boşluk",         "name_ar": "فراغ",             "name_es": "Vacío",          "name_fr": "Vide",            "name_uk": "Порожнеча",       "name_pl": "Pustka",          "name_el": "Κενό",           "name_ta": "வெறுமை"},
    {"id": "verlorenheit",     "emoji": "🧭", "category": "schwere", "name_de": "Verlorenheit",     "name_vi": "Lạc lõng",              "name_en": "Lostness",       "name_tr": "Kaybolmuşluk",   "name_ar": "ضياع",             "name_es": "Desorientación", "name_fr": "Égarement",       "name_uk": "Загубленість",    "name_pl": "Zagubienie",      "name_el": "Χαμένος",        "name_ta": "தொலைந்த உணர்வு"},
    {"id": "hoffnungslosigkeit","emoji": "🖤","category": "schwere", "name_de": "Hoffnungslosigkeit","name_vi": "Tuyệt vọng",           "name_en": "Hopelessness",   "name_tr": "Umutsuzluk",     "name_ar": "يأس",              "name_es": "Desesperanza",   "name_fr": "Désespoir",       "name_uk": "Безнадія",        "name_pl": "Beznadziejność",  "name_el": "Απελπισία",      "name_ta": "நம்பிக்கையின்மை"},
    {"id": "verlassenheit",    "emoji": "🚶", "category": "schwere", "name_de": "Verlassenheit",    "name_vi": "Cảm giác bị bỏ rơi",   "name_en": "Abandonment",    "name_tr": "Terk edilmişlik","name_ar": "هجران",            "name_es": "Abandono",       "name_fr": "Abandon",         "name_uk": "Покинутість",     "name_pl": "Opuszczenie",     "name_el": "Εγκατάλειψη",    "name_ta": "கைவிடப்பட்ட உணர்வு"},

    # ── Sturm & Reibung (storm) ───────────────────────────────────────────────
    {"id": "wut",           "emoji": "😤", "category": "sturm",   "name_de": "Wut",              "name_vi": "Tức giận",              "name_en": "Anger",          "name_tr": "Öfke",           "name_ar": "غضب",              "name_es": "Ira",            "name_fr": "Colère",          "name_uk": "Гнів",            "name_pl": "Gniew",           "name_el": "Θυμός",          "name_ta": "கோபம்"},
    {"id": "frustration",   "emoji": "😩", "category": "sturm",   "name_de": "Frustration",      "name_vi": "Bực bội",               "name_en": "Frustration",    "name_tr": "Hayal kırıklığı","name_ar": "إحباط",            "name_es": "Frustración",    "name_fr": "Frustration",     "name_uk": "Розчарування",    "name_pl": "Frustracja",      "name_el": "Ματαίωση",       "name_ta": "விரக்தி"},
    {"id": "aerger",        "emoji": "😠", "category": "sturm",   "name_de": "Ärger",            "name_vi": "Cáu giận",              "name_en": "Annoyance",      "name_tr": "Kızgınlık",      "name_ar": "انزعاج",           "name_es": "Enfado",         "name_fr": "Agacement",       "name_uk": "Роздратування",   "name_pl": "Irytacja",        "name_el": "Εκνευρισμός",    "name_ta": "எரிச்சல்"},
    {"id": "neid",          "emoji": "👀", "category": "sturm",   "name_de": "Neid",             "name_vi": "Ghen tị",               "name_en": "Envy",           "name_tr": "Kıskançlık",     "name_ar": "حسد",              "name_es": "Envidia",        "name_fr": "Envie",           "name_uk": "Заздрість",       "name_pl": "Zazdrość",        "name_el": "Φθόνος",         "name_ta": "பொறாமை"},
    {"id": "eifersucht",    "emoji": "💚", "category": "sturm",   "name_de": "Eifersucht",       "name_vi": "Ghen tuông",            "name_en": "Jealousy",       "name_tr": "Kıskançlık",     "name_ar": "غيرة",             "name_es": "Celos",          "name_fr": "Jalousie",        "name_uk": "Ревнощі",         "name_pl": "Zazdrość",        "name_el": "Ζήλια",          "name_ta": "ஊடல்"},
    {"id": "groll",         "emoji": "😒", "category": "sturm",   "name_de": "Groll",            "name_vi": "Oán giận",              "name_en": "Resentment",     "name_tr": "Kin",            "name_ar": "ضغينة",            "name_es": "Rencor",         "name_fr": "Rancœur",         "name_uk": "Образа",          "name_pl": "Uraza",           "name_el": "Μνησικακία",     "name_ta": "மனக்கசப்பு"},
    {"id": "ungeduld",      "emoji": "⏰", "category": "sturm",   "name_de": "Ungeduld",         "name_vi": "Thiếu kiên nhẫn",       "name_en": "Impatience",     "name_tr": "Sabırsızlık",    "name_ar": "نفاد الصبر",       "name_es": "Impaciencia",    "name_fr": "Impatience",      "name_uk": "Нетерплячість",   "name_pl": "Niecierpliwość",  "name_el": "Ανυπομονησία",   "name_ta": "பொறுமையின்மை"},
    {"id": "gereiztheit",   "emoji": "😡", "category": "sturm",   "name_de": "Gereiztheit",      "name_vi": "Dễ nổi nóng",           "name_en": "Irritability",   "name_tr": "Sinirlilik",     "name_ar": "عصبية",            "name_es": "Irritabilidad",  "name_fr": "Irritabilité",    "name_uk": "Дратівливість",   "name_pl": "Drażliwość",      "name_el": "Ευερεθιστότητα", "name_ta": "எரிமலை உணர்வு"},
    {"id": "trotz",         "emoji": "✊", "category": "sturm",   "name_de": "Trotz",            "name_vi": "Bướng bỉnh",            "name_en": "Defiance",       "name_tr": "İnat",           "name_ar": "تحدٍّ",            "name_es": "Rebeldía",       "name_fr": "Défiance",        "name_uk": "Упертість",       "name_pl": "Upór",            "name_el": "Πείσμα",         "name_ta": "பிடிவாதம்"},
    {"id": "empoerung",     "emoji": "🗯️", "category": "sturm",   "name_de": "Empörung",         "name_vi": "Phẫn nộ",               "name_en": "Outrage",        "name_tr": "Öfke",           "name_ar": "سخط",              "name_es": "Indignación",    "name_fr": "Indignation",     "name_uk": "Обурення",        "name_pl": "Oburzenie",       "name_el": "Αγανάκτηση",     "name_ta": "ஆவேசம்"},
    {"id": "rebellion",     "emoji": "🏴", "category": "sturm",   "name_de": "Rebellion",        "name_vi": "Phản kháng",            "name_en": "Rebellion",      "name_tr": "İsyan",          "name_ar": "تمرد",             "name_es": "Rebelión",       "name_fr": "Rébellion",       "name_uk": "Бунт",            "name_pl": "Bunt",            "name_el": "Επανάσταση",     "name_ta": "எதிர்ப்பு"},

    # ── Angst & Schutz (fear) ─────────────────────────────────────────────────
    {"id": "angst_gefuehl",    "emoji": "😨", "category": "angst",   "name_de": "Angst",            "name_vi": "Sợ hãi",                "name_en": "Fear",           "name_tr": "Korku",          "name_ar": "خوف",              "name_es": "Miedo",          "name_fr": "Peur",            "name_uk": "Страх",           "name_pl": "Strach",          "name_el": "Φόβος",          "name_ta": "பயம்"},
    {"id": "sorge",            "emoji": "😟", "category": "angst",   "name_de": "Sorge",            "name_vi": "Lo lắng",               "name_en": "Worry",          "name_tr": "Endişe",         "name_ar": "قلق",              "name_es": "Preocupación",   "name_fr": "Souci",           "name_uk": "Тривога",         "name_pl": "Troska",          "name_el": "Ανησυχία",       "name_ta": "கவலை"},
    {"id": "unsicherheit",     "emoji": "🫣", "category": "angst",   "name_de": "Unsicherheit",     "name_vi": "Bất an",                "name_en": "Insecurity",     "name_tr": "Güvensizlik",    "name_ar": "انعدام الأمان",    "name_es": "Inseguridad",    "name_fr": "Insécurité",      "name_uk": "Невпевненість",   "name_pl": "Niepewność",      "name_el": "Ανασφάλεια",     "name_ta": "நிச்சயமின்மை"},
    {"id": "panik",            "emoji": "😱", "category": "angst",   "name_de": "Panik",            "name_vi": "Hoảng loạn",            "name_en": "Panic",          "name_tr": "Panik",          "name_ar": "ذعر",              "name_es": "Pánico",         "name_fr": "Panique",         "name_uk": "Паніка",          "name_pl": "Panika",          "name_el": "Πανικός",        "name_ta": "பீதி"},
    {"id": "nervositaet",      "emoji": "😬", "category": "angst",   "name_de": "Nervosität",       "name_vi": "Hồi hộp",               "name_en": "Nervousness",    "name_tr": "Gerginlik",      "name_ar": "توتر",             "name_es": "Nerviosismo",    "name_fr": "Nervosité",       "name_uk": "Нервозність",     "name_pl": "Nerwowość",       "name_el": "Νευρικότητα",    "name_ta": "பதட்டம்"},
    {"id": "misstrauen",       "emoji": "🤨", "category": "angst",   "name_de": "Misstrauen",       "name_vi": "Nghi ngờ",              "name_en": "Distrust",       "name_tr": "Güvensizlik",    "name_ar": "ريبة",             "name_es": "Desconfianza",   "name_fr": "Méfiance",        "name_uk": "Недовіра",        "name_pl": "Nieufność",       "name_el": "Δυσπιστία",      "name_ta": "சந்தேகம்"},
    {"id": "bedrohung",        "emoji": "⚠️", "category": "angst",   "name_de": "Bedrohung",        "name_vi": "Bị đe dọa",             "name_en": "Threat",         "name_tr": "Tehdit",         "name_ar": "تهديد",            "name_es": "Amenaza",        "name_fr": "Menace",          "name_uk": "Загроза",         "name_pl": "Zagrożenie",      "name_el": "Απειλή",         "name_ta": "அச்சுறுத்தல்"},
    {"id": "kontrollverlust",  "emoji": "🌀", "category": "angst",   "name_de": "Kontrollverlust",  "name_vi": "Mất kiểm soát",         "name_en": "Loss of control","name_tr": "Kontrol kaybı",  "name_ar": "فقدان السيطرة",    "name_es": "Pérdida de control","name_fr": "Perte de contrôle","name_uk": "Втрата контролю", "name_pl": "Utrata kontroli", "name_el": "Απώλεια ελέγχου","name_ta": "கட்டுப்பாட்டை இழக்கும் உணர்வு"},
    {"id": "ueberwachsamkeit", "emoji": "👁️", "category": "angst",   "name_de": "Überwachsamkeit",  "name_vi": "Cảnh giác quá mức",     "name_en": "Hypervigilance", "name_tr": "Aşırı tetikte",  "name_ar": "فرط اليقظة",       "name_es": "Hipervigilancia","name_fr": "Hypervigilance",   "name_uk": "Надпильність",    "name_pl": "Nadmierna czujność","name_el": "Υπερεπαγρύπνηση","name_ta": "மிகுந்த விழிப்புணர்வு"},

    # ── Verdeckte Schatten (shadows) ──────────────────────────────────────────
    {"id": "resignation",       "emoji": "😔", "category": "schatten","name_de": "Resignation",      "name_vi": "Buông xuôi",            "name_en": "Resignation",    "name_tr": "Boyun eğme",     "name_ar": "استسلام",          "name_es": "Resignación",    "name_fr": "Résignation",     "name_uk": "Смирення",        "name_pl": "Rezygnacja",      "name_el": "Παραίτηση",      "name_ta": "விரக்தி துறத்தல்"},
    {"id": "bitterkeit",        "emoji": "🍋", "category": "schatten","name_de": "Bitterkeit",       "name_vi": "Cay đắng",              "name_en": "Bitterness",     "name_tr": "Acılık",         "name_ar": "مرارة",            "name_es": "Amargura",       "name_fr": "Amertume",        "name_uk": "Гіркота",         "name_pl": "Gorycz",          "name_el": "Πικρία",         "name_ta": "கசப்பு"},
    {"id": "selbstzweifel",     "emoji": "🪞", "category": "schatten","name_de": "Selbstzweifel",    "name_vi": "Tự nghi ngờ",           "name_en": "Self-doubt",     "name_tr": "Özgüven eksikliği","name_ar": "شك بالنفس",       "name_es": "Inseguridad",    "name_fr": "Doute de soi",    "name_uk": "Невпевненість у собі","name_pl": "Zwątpienie w siebie","name_el": "Αυτοαμφιβολία","name_ta": "சுயசந்தேகம்"},
    {"id": "selbstverurteilung","emoji": "⚖️", "category": "schatten","name_de": "Selbstverurteilung","name_vi": "Tự trách móc",         "name_en": "Self-judgment",  "name_tr": "Kendini yargılama","name_ar": "محاسبة الذات",    "name_es": "Autocrítica",    "name_fr": "Auto-jugement",   "name_uk": "Самозасудження",  "name_pl": "Samoosądzanie",   "name_el": "Αυτοκατάκριση",  "name_ta": "சுயகுற்றவுணர்வு"},
    {"id": "verhaertung",       "emoji": "🪨", "category": "schatten","name_de": "Verhärtung",       "name_vi": "Chai sạn",              "name_en": "Hardening",      "name_tr": "Katılaşma",      "name_ar": "تصلب",             "name_es": "Endurecimiento", "name_fr": "Endurcissement",  "name_uk": "Зачерствіння",    "name_pl": "Zatwardziałość",  "name_el": "Σκλήρυνση",      "name_ta": "மனகடினம்"},
    {"id": "taubheit",          "emoji": "🧊", "category": "schatten","name_de": "Taubheit",         "name_vi": "Tê liệt cảm xúc",       "name_en": "Numbness",       "name_tr": "Hissizlik",      "name_ar": "خدر",              "name_es": "Insensibilidad", "name_fr": "Engourdissement", "name_uk": "Заціпеніння",     "name_pl": "Odrętwienie",     "name_el": "Μούδιασμα",      "name_ta": "உணர்வற்ற நிலை"},
    {"id": "zynismus",          "emoji": "🎭", "category": "schatten","name_de": "Zynismus",         "name_vi": "Bi quan châm biếm",     "name_en": "Cynicism",       "name_tr": "Sinizm",         "name_ar": "سخرية",            "name_es": "Cinismo",        "name_fr": "Cynisme",         "name_uk": "Цинізм",          "name_pl": "Cynizm",          "name_el": "Κυνισμός",       "name_ta": "நம்பிக்கையற்ற நகை"},
    {"id": "hoffnungsmuedigkeit","emoji": "🕯️","category": "schatten","name_de": "Hoffnungsmüdigkeit","name_vi": "Mệt mỏi vì hy vọng",  "name_en": "Hope fatigue",   "name_tr": "Umut yorgunluğu","name_ar": "إرهاق الأمل",      "name_es": "Fatiga de esperanza","name_fr": "Fatigue d'espoir","name_uk": "Втома від надії", "name_pl": "Zmęczenie nadzieją","name_el": "Κόπωση ελπίδας","name_ta": "நம்பிக்கை சோர்வு"},
]
